services:
  - type: web
    name: faleh-law-office
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT final_working:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: faleh-postgres
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
    healthCheckPath: /
    
databases:
  - name: faleh-postgres
    databaseName: faleh_db
    user: faleh_user
    plan: free
